### ISSUE TITLE
Server isn't stopped after codecept exit

### ISSUE THREAD

**Issue by etki** [tiger-seo/PhpBuiltinServer#17]
Hi, i just wanted to report that PHP server brought up by this extension is never switched off on my system (Lubuntu 14.04 x64, php 5.5.9), even though i clearly see `stopServer` method being registered as shutdown function. I can see it in `ps aux` output and i can access it directly as well. It also doesn't affect any latter codeception runs, it just doesn't turn off (but nothing else breaks).

**Comment by tiger-seo** [comment]
hello
please, check https://github.com/tiger-seo/PhpBuiltinServer/pull/4

**Comment by etki** [comment]
@tiger-seo Sorry for monstrous delay.
I had some problems after updating, but i believe they are not related to this extension. Pull request seem to shut down process correctly.
