### ISSUE TITLE
Consider making startServer() and stopServer() public

### ISSUE THREAD

**Issue by airdrummingfool** [tiger-seo/PhpBuiltinServer#23]
Would you consider accepting a PR that would make the `startServer()` and `stopServer()` methods `public`? For backwards compatibility, I can leave the `startServer()` call in `__construct()` (`startServer()` already protects against starting more than one server at a time) and the `stopServer()` call in `__destruct()`. Even better, I can add an `autostart` config option to disable the `startServer()` call in `__config()` for those of us who want to use start/stop explicitly.

I'm writing a Codecept `Helper` that wraps this extension in order to capture outgoing request data, in order to facilitate testing webhooks (my server sending a request to an external server on certain events). Right now I have no way to control when the server stops, and to start it I have to create a new instance. Making the start and stop methods public gives that extra measure of control, without making usage any more complicated for those who already use it.

**Comment by tiger-seo** [comment]
feature has been merged, thanks :wink:
