### ISSUE TITLE
Cannot run PHP 7 + coverage tests: cURL error 7: couldn't connect to host

### ISSUE THREAD

**Issue by oparoz** [tiger-seo/PhpBuiltinServer#25]
Also filed in https://github.com/Codeception/Codeception/issues/2730

I launch 2 commands in a row on Travis

```
$ php vendor/bin/codecept run acceptance --env firefox
$ php vendor/bin/codecept run api,integration,unit -vvv --coverage --coverage-xml --coverage-html 
```

The second one will fail with this error message

>[GuzzleHttp\Exception\ConnectException]  
  cURL error 7: couldn't connect to host  

 in tests/_output/phpbuiltinserver.errors.txt, I get:

> [Wed Jan 13 14:36:32 2016] Failed to listen on localhost:8000 (reason: Address already in use)
[Wed Jan 13 14:36:40 2016] ::1:48142 [200]: /c3/report/clear

or 

>[Wed Jan 20 11:28:02 2016] ::1:50413 [200]: /index.php/apps/gallery/files/list?location=&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bapplication%2Fpostscript&features=&etag
[Wed Jan 20 11:28:10 2016] ::1:50425 [200]: /c3/report/clear

This does not happen on older version of PHP

**Comment by oparoz** [comment]
Actually, on the most recent run, using v1.2.2, it doesn't say "Address already in use", so that may be a red herring.

```
[Wed Jan 20 11:28:02 2016] ::1:50413 [200]: /index.php/apps/gallery/files/list?location=&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bapplication%2Fpostscript&features=&etag
[Wed Jan 20 11:28:10 2016] ::1:50425 [200]: /c3/report/clear
```

**Comment by oparoz** [comment]
> /home/travis/build.sh: line 45: 12400 Segmentation fault (core dumped) php -S localhost:8000 -t ../.. > /dev/null 2>&1

I don't think it's related to this extension

**Comment by tiger-seo** [comment]
:relieved:
