### ISSUE TITLE
Exception name change in Codecetption

### ISSUE THREAD

**Issue by jjpmann** [tiger-seo/PhpBuiltinServer#31]
ModuleConfig was changed to ModuleConfigException in v2.1.0

> PHP Fatal error:  Uncaught Error: Class 'Codeception\Exception\ModuleConfig' not found in vendor/codeception/phpbuiltinserver/src/Codeception/Extension/PhpBuiltinServer.php:119

**Comment by Azuka** [comment]
👍  Can we get this into 1.2?
